### ISSUE TITLE
[error] 501#501: *136 failed to run log_by_lua*: /tmp/lua-resty-rocketmq/lib/resty/rocketmq/core.lua:272: API disabled in the context of log_by_lua*

### ISSUE THREAD

**Issue by wuguaner** [yuz10/lua-resty-rocketmq#1]
2021/07/22 09:27:55 [error] 501#501: *136 failed to run log_by_lua*: /tmp/lua-resty-rocketmq/lib/resty/rocketmq/core.lua:272: API disabled in the context of log_by_lua*
stack traceback:
	[C]: in function 'ngx_socket_tcp'
	/tmp/lua-resty-rocketmq/lib/resty/rocketmq/core.lua:272: in function 'doReqeust'
	/tmp/lua-resty-rocketmq/lib/resty/rocketmq/core.lua:318: in function 'getTopicRouteInfoFromNameserver'
	/tmp/lua-resty-rocketmq/lib/resty/rocketmq/client.lua:158: in function 'tryToFindTopicPublishInfo'
	/tmp/lua-resty-rocketmq/lib/resty/rocketmq/producer.lua:81: in function 'produce'
	log_by_lua(default.conf:64):34: in main chunk while logging request, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1"

**Comment by yuz10** [comment]
not supported in nginx log phrase, please run produce in ngx.timer.
```
ngx.timer.at(0, function()
    p:produce("TopicTest", "message")
end)
```

**Comment by wuguaner** [comment]
2021/07/22 10:12:15 [error] 523#523: *153 [lua] log_by_lua(default.conf:69):41: send err:nil while logging request, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1"

**Comment by wuguaner** [comment]
location / {                                                                            
        root   /usr/local/openresty/nginx/html;                                             
        index  index.html index.htm;                                                        
        log_by_lua '                                                                        
            local cjson = require "cjson"                                                   
            local producer = require "resty.rocketmq.producer"                              
                                                              
            local nameservers = {                             
                "10.233.16.118:9876",                         
            }                                                 
                                                              
            local log_json = {}                               
            log_json["uri"]=ngx.var.uri                       
            log_json["args"]=ngx.var.args                     
            log_json["host"]=ngx.var.host                     
            log_json["request_body"]=ngx.var.request_body     
            log_json["remote_addr"] = ngx.var.remote_addr     
            log_json["remote_user"] = ngx.var.remote_user     
            log_json["time_local"] = ngx.var.time_local       
            log_json["status"] = ngx.var.status               
            log_json["body_bytes_sent"] = ngx.var.body_bytes_sent
            log_json["http_referer"] = ngx.var.http_referer      
            log_json["http_user_agent"] = ngx.var.http_user_agent
            log_json["http_x_forwarded_for"] = ngx.var.http_x_forwarded_for
            log_json["upstream_response_time"] = ngx.var.upstream_response_time
            log_json["request_time"] = ngx.var.request_time                    
                                                                               
            local message = cjson.encode(log_json)                             
            local p = producer.new(nameservers, "produce_group")               
            -- set acl                                                         
            local aclHook = require("resty.rocketmq.acl_rpchook").new("rocketmq2","ymsl@2021")
            p:addRPCHook(aclHook)                                                             
                                                                                              
            -- use tls mode                                                                   
            p:setUseTLS(true)                                                                 
                                                                                              
            ngx.timer.at(0, function()                                                        
                p:produce("TopicTest", "message")                                             
            end)                                                                              
            -- local res, err = p:produce("TopicTest", message)                               
            if not res then                                                                   
                ngx.log(ngx.ERR, "send err:", err)                                            
                return                                                                        
            end                                                                               
        ';                                                                                    
    }

**Comment by wuguaner** [comment]
I've found the problem。
ngx.var.request_body not supported in nginx log phrase

**Comment by wuguaner** [comment]
Thanks！
