### ISSUE TITLE
How to connect to aliyun rocketmq

### ISSUE THREAD

**Issue by ChidoriZZ** [yuz10/lua-resty-rocketmq#9]
I'm connected to Alicloud's rocketmq and The corresponding nameservers information is configured,But when I start nginx I get this exception，How can I handle this？
![image](https://user-images.githubusercontent.com/49048553/204002145-513cac74-6d38-4921-8645-bf190e63f631.png)

<img width="999" alt="image" src="https://user-images.githubusercontent.com/49048553/204002046-996dae5b-32b7-4ed4-aa98-4c0d6072a95b.png">

**Comment by yuz10** [comment]
try removing http:// in nameservers

**Comment by ChidoriZZ** [comment]
I've tried it, and it's still .I tried to install an mq myself, and then the connection test, is OK.
![2371669787577_ pic](https://user-images.githubusercontent.com/49048553/204729845-d9fad349-c86a-407b-bc10-50bbb3b21f7c.jpg)

**Comment by yuz10** [comment]
use nslookup to find the ip address of the domain, and set the ip
note that  you should specify a namespace if you use aliyun rocketmq, for example:
```lua
local producer = require "resty.rocketmq.producer"
local nameservers = { "47.97.99.104:80" } -- ip address of aliyun rocketmq endpoint, like "MQ_INST_1656704317097747_BYUJxDgJ.cn-hangzhou.mq.aliyuncs.com"
local p, err = producer.new(nameservers)
if not p then
    print("create producer err:", err)
    return
end
local aclHook = require("resty.rocketmq.acl_rpchook").new("ak","sk") -- ak and sk of aliyun account
p:addRPCHook(aclHook)

local res, err = p:send("MQ_INST_1656704317097747_BYUJxDgJ%TopicTest", "halo world") -- the instance id + "%" + topic
if not res then
    print("send err:", err)
    return
end
print("send success: " .. cjson.encode(res.sendResult))
```

**Comment by ChidoriZZ** [comment]
Thank you, this time is OK. In addition, I have another question to consult. If the MQ's **tag** needs to be specified, how to deal with it

**Comment by yuz10** [comment]
tag is used to filter messages when consume message, you do not need specify tag if you dont filter message

**Comment by ChidoriZZ** [comment]
I see. Thanks for the guidance
